version: '3.3'

services:

  db:
    image: mysql
    container_name: convidados-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: festa
    restart: always
    networks:
      - workspace
    expose:
      - 3306


  convidados-api:
    build:
      dockerfile: Dockerfile
    container_name: convidados-api
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - workspace
    depends_on:
      - db

networks:
  workspace:
    driver: bridge
